### ISSUE TITLE
Apple's Calendar doesn't support the date format used

### ISSUE THREAD

**Issue by BasO** [freaktechnik/twitch-events-ical#23]
The DTSTART and DTEND values are currently formatted as, e.g., 2019-01-14T19:30:00.000Z

Apple Calendar doesn't support this format, thus no events show up in the calendar subscription, and the events can't be imported. It appears that the format 20190114T193000 does work (leaving out the interpunction and the trailing .000Z).

**Comment by freaktechnik** [comment]
From what I understand `DTSTART:2019-01-15T23:00:00.000Z` etc. is pretty standard iCal dates. I'd love to see what apple actually supports.

**Comment by BasO** [comment]
Sorry, posted too early on accident. I did a lot of trial and error and when I change the DTSTART and DTEND values to the format of 20190114T193000 (no interpunction and no trialing .000Z) the events are correctly imported.

**Comment by freaktechnik** [comment]
The problem with not having the "Z" is that some clients will interpret the date with the wrong timezone. The miliseconds should indeed not be required, I'll look into that.
